# Generated by Django 4.2.3 on 2024-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegen', '0007_remove_reportdownloadfile_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdownloadfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reportdownloadfile',
            name='file',
            field=models.FileField(upload_to='reports/%Y/%m/%d/'),
        ),
    ]
