# Generated by Django 4.2.3 on 2024-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_reportonefields_table_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportonefields',
            name='table_position',
        ),
        migrations.AddField(
            model_name='reportonetable',
            name='table_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
