# Generated by Django 4.2.3 on 2024-05-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_department'),
        ('analytics', '0003_remove_reportonefields_table_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportonetable',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.department'),
        ),
    ]
