# Generated by Django 4.2.3 on 2024-06-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_partner_contract'),
        ('analytics', '0004_alter_reportonetable_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpdateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Отчет')),
                ('date', models.DateTimeField(auto_now=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.department', verbose_name='Подразделение')),
            ],
        ),
    ]
