# Generated by Django 4.2.3 on 2024-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('send_list', models.TextField(verbose_name='Список получивших')),
                ('dont_send_list', models.TextField(verbose_name='Список не получивших')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
    ]
