# Generated by Django 4.2.3 on 2023-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriescategoryitem',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='census',
            name='task',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер задачи'),
        ),
    ]
