# Generated by Django 4.2.3 on 2023-10-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='accessories_category',
        ),
        migrations.AddField(
            model_name='census',
            name='accessories_category',
            field=models.ManyToManyField(blank=True, default=None, to='census.accessoriescategory', verbose_name='Категории аксессуаров'),
        ),
    ]
