# Generated by Django 4.2.3 on 2024-02-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bothers',
            name='category',
            field=models.CharField(blank=True, default=True, max_length=200, null=True, verbose_name='Другая категория'),
        ),
        migrations.AddField(
            model_name='b2bothers',
            name='volume',
            field=models.CharField(blank=True, default=True, max_length=200, null=True, verbose_name='Другой объем'),
        ),
        migrations.AddField(
            model_name='b2bothers',
            name='volume_value',
            field=models.CharField(blank=True, default=True, max_length=200, null=True, verbose_name='Другая категория'),
        ),
        migrations.AlterField(
            model_name='b2bothers',
            name='equipment',
            field=models.CharField(blank=True, default=True, max_length=200, null=True, verbose_name='Другой парк техники'),
        ),
    ]
