# Generated by Django 4.2.3 on 2023-10-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_remove_census_accessories_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='accessories_category',
        ),
        migrations.AddField(
            model_name='census',
            name='accessories_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.accessoriescategory', verbose_name='Категории аксессуаров'),
        ),
    ]
