# Generated by Django 4.2.3 on 2024-02-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_b2bothers_category_b2bothers_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bothers',
            name='census',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='census.census'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='census',
            name='b2b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='census.b2bothers'),
        ),
    ]
