# Generated by Django 4.2.3 on 2024-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_b2bothers_census_alter_census_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bothers',
            name='vector',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='b2bothers',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Другая категория'),
        ),
        migrations.AlterField(
            model_name='b2bothers',
            name='equipment',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Другой парк техники'),
        ),
        migrations.AlterField(
            model_name='b2bothers',
            name='volume',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Другой объем'),
        ),
        migrations.AlterField(
            model_name='b2bothers',
            name='volume_value',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Другая категория'),
        ),
    ]
