# Generated by Django 4.2.3 on 2023-10-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_alter_census_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='uploads/None/')),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.census', verbose_name='Сенсус')),
            ],
            options={
                'verbose_name': 'Фото Сенсус',
                'verbose_name_plural': 'Фото Сенсусы',
                'ordering': ['-created_date'],
            },
        ),
    ]
