# Generated by Django 4.2.3 on 2023-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_remove_census_accessories_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='vector',
        ),
        migrations.AddField(
            model_name='census',
            name='vector',
            field=models.ManyToManyField(blank=True, default=None, to='census.pointvectors', verbose_name='Направленность'),
        ),
    ]
