# Generated by Django 4.2.3 on 2023-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_remove_census_vector_census_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='closing',
            field=models.BooleanField(default=False, verbose_name='Точка закрыта'),
        ),
        migrations.AddField(
            model_name='census',
            name='inn',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='census',
            name='organizations_name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Название организации'),
        ),
    ]
