# Generated by Django 4.2.3 on 2023-10-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_resultgroup_name'),
        ('census', '0005_census_closing_census_inn_census_organizations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.pointcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='census',
            name='point_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Вывеска'),
        ),
        migrations.AlterField(
            model_name='census',
            name='point_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.pointtypes', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='census',
            name='providers',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='census.providerlist', verbose_name='Основные поставщики'),
        ),
        migrations.AlterField(
            model_name='census',
            name='result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.result', verbose_name='Результат встречи'),
        ),
        migrations.AlterField(
            model_name='census',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.task', verbose_name='Задача'),
        ),
    ]
