# Generated by Django 4.2.3 on 2023-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_alter_censusfiles_census_alter_censusfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение'),
        ),
    ]
