# Generated by Django 4.2.3 on 2024-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_remove_census_other_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='vector',
        ),
    ]
