# Generated by Django 4.2.3 on 2023-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_alter_census_category_alter_census_point_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='census',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название'),
        ),
    ]
