# Generated by Django 4.2.3 on 2024-02-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_remove_census_vector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='volume',
            new_name='volume_name',
        ),
    ]
