# Generated by Django 4.2.3 on 2023-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_census_decision_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='lukoil_debit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='motul_debit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='oil_debit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='rowe_debit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
