# Generated by Django 4.2.3 on 2024-02-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_rename_volume_others_volume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='vector',
        ),
    ]
