# Generated by Django 4.2.3 on 2023-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_alter_census_lukoil_debit_alter_census_motul_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusfiles',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
