# Generated by Django 4.2.3 on 2023-11-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_companydatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='dadata',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='census.companydatabase'),
        ),
    ]
