# Generated by Django 4.2.3 on 2024-02-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_others_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='category',
        ),
    ]
