# Generated by Django 4.2.3 on 2024-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0011_remove_others_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
