# Generated by Django 4.2.3 on 2023-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0011_census_dadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydatabase',
            name='address_latitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Широта_DADATA'),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='address_longitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Долгота_DADATA'),
        ),
    ]
