# Generated by Django 4.2.3 on 2024-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_equipmentlist_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
