# Generated by Django 4.2.3 on 2023-11-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_companydatabase_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='liquidation_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата ликвидации'),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='registration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='companydatabase',
            name='status',
            field=models.DateField(blank=True, choices=[('ACTIVE', 'действующая'), ('LIQUIDATING', 'ликвидируется'), ('LIQUIDATED', 'ликвидирована'), ('BANKRUPT', 'банкротство'), ('REORGANIZING', 'в процессе присоединения к другому юр.лицу, с последующей ликвидацией')], default=None, null=True, verbose_name='статус организации'),
        ),
    ]
