# Generated by Django 4.2.3 on 2024-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_alter_equipmentlist_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='equipment',
            new_name='equipment_name',
        ),
        migrations.AddField(
            model_name='others',
            name='equipment_value',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
