# Generated by Django 4.2.3 on 2023-11-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_alter_companydatabase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='ogrn',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='ОГРН'),
        ),
    ]
