# Generated by Django 4.2.3 on 2024-02-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_remove_equipmentlist_value_equipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.equipmentlist'),
        ),
    ]
