# Generated by Django 4.2.3 on 2023-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_alter_companydatabase_ogrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydatabase',
            name='oktmo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='ОКТМО'),
        ),
    ]
