# Generated by Django 4.2.3 on 2023-11-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0017_alter_companydatabase_oktmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydatabase',
            name='actuality_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата последних изменений'),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='liquidation_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата ликвидации'),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='ogrn_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи ОГРН'),
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='registration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='дата регистрации'),
        ),
    ]
