# Generated by Django 4.2.3 on 2024-02-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0017_alter_census_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='equipment',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_equipments', to='census.equipmentlist'),
        ),
    ]
