# Generated by Django 4.2.3 on 2024-02-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0018_alter_census_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentItem',
        ),
    ]
