# Generated by Django 4.2.3 on 2023-11-13 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0018_companydatabase_actuality_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydatabase',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydatabase',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
