# Generated by Django 4.2.3 on 2024-02-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0019_delete_equipmentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=500, verbose_name='Значение')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('census', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='census.census')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.equipmentlist')),
            ],
        ),
        migrations.AlterField(
            model_name='census',
            name='equipment',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_equipments', to='census.equipmentitem'),
        ),
    ]
