# Generated by Django 4.2.3 on 2024-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_department_volume_volumeitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='equipmentlist',
            options={'verbose_name': 'Парк техники', 'verbose_name_plural': 'Парк техники'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Объем', 'verbose_name_plural': 'Объем'},
        ),
        migrations.RemoveField(
            model_name='volumeitem',
            name='name',
        ),
        migrations.AddField(
            model_name='volumeitem',
            name='value',
            field=models.CharField(default=0, max_length=500, verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='VolumeItemValue',
        ),
    ]
