# Generated by Django 4.2.3 on 2024-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_equipmentitem_alter_census_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='equipment_value',
        ),
        migrations.AddField(
            model_name='census',
            name='basics',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер основания'),
        ),
    ]
