# Generated by Django 4.2.3 on 2024-03-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0021_remove_others_equipment_value_census_basics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='accessories_brands',
        ),
        migrations.RemoveField(
            model_name='census',
            name='accessories_category',
        ),
        migrations.RemoveField(
            model_name='census',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='census',
            name='oils',
        ),
        migrations.AlterField(
            model_name='providerlist',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
