# Generated by Django 4.2.3 on 2024-01-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0021_alter_department_options_alter_equipmentlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumeitem',
            name='census',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='census.census'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='census',
            name='volume',
        ),
        migrations.AddField(
            model_name='census',
            name='volume',
            field=models.ManyToManyField(blank=True, null=True, related_name='census_volumes', to='census.volumeitem'),
        ),
    ]
