# Generated by Django 4.2.3 on 2024-01-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0022_volumeitem_census_remove_census_volume_census_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumeitem',
            name='is_active',
        ),
    ]
