# Generated by Django 4.2.3 on 2024-01-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0023_remove_volumeitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='volume',
            field=models.ManyToManyField(blank=True, related_name='census_volumes', to='census.volumeitem'),
        ),
    ]
