# Generated by Django 4.2.3 on 2024-03-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0023_others_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='lukoil_debit',
        ),
        migrations.RemoveField(
            model_name='census',
            name='motul_debit',
        ),
        migrations.RemoveField(
            model_name='census',
            name='oil_debit',
        ),
        migrations.RemoveField(
            model_name='census',
            name='rowe_debit',
        ),
        migrations.RemoveField(
            model_name='census',
            name='vitex_debit',
        ),
    ]
