# Generated by Django 4.2.3 on 2024-03-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0024_remove_census_lukoil_debit_remove_census_motul_debit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Фамилия')),
                ('lastname', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ЛПР_email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('function', models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность')),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_decisions', to='census.census')),
            ],
        ),
        migrations.AddField(
            model_name='census',
            name='decision',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision', to='census.decision', verbose_name='Контактное лицо'),
        ),
    ]
