# Generated by Django 4.2.3 on 2024-03-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0025_decision_census_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='decision_email',
        ),
        migrations.RemoveField(
            model_name='census',
            name='decision_firstname',
        ),
        migrations.RemoveField(
            model_name='census',
            name='decision_function',
        ),
        migrations.RemoveField(
            model_name='census',
            name='decision_lastname',
        ),
        migrations.RemoveField(
            model_name='census',
            name='decision_phone',
        ),
        migrations.RemoveField(
            model_name='census',
            name='decision_surname',
        ),
    ]
