# Generated by Django 4.2.3 on 2024-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0025_alter_pointcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectors',
            name='slug',
            field=models.SlugField(blank=True, default=True, null=True),
        ),
    ]
