# Generated by Django 4.2.3 on 2024-03-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0026_remove_census_decision_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OilList',
        ),
    ]
