# Generated by Django 4.2.3 on 2024-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0026_pointvectors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectors',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
