# Generated by Django 4.2.3 on 2024-03-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0027_delete_oillist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriescategoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filterlist',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='pointtypes',
            options={'ordering': ['-created_date'], 'verbose_name': 'Тип точки', 'verbose_name_plural': 'Типы точек'},
        ),
        migrations.AlterModelOptions(
            name='stotypelist',
            options={'ordering': ['-created_date'], 'verbose_name': 'Типы СТО торговой точки', 'verbose_name_plural': 'Типы СТО торговой точки'},
        ),
        migrations.DeleteModel(
            name='AccessoriesCategory',
        ),
        migrations.DeleteModel(
            name='AccessoriesCategoryItem',
        ),
        migrations.DeleteModel(
            name='FilterList',
        ),
    ]
