# Generated by Django 4.2.3 on 2024-03-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0028_remove_accessoriescategoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carslist',
            options={'ordering': ['-created_date'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='providerlist',
            options={'ordering': ['-created_date'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
