# Generated by Django 4.2.3 on 2024-03-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0029_alter_carslist_options_alter_providerlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointvectorsselectitem',
            options={'ordering': ['-created_date'], 'verbose_name': 'Выбираемый объем', 'verbose_name_plural': 'Выбираемые объемы'},
        ),
    ]
