# Generated by Django 4.2.3 on 2024-01-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0029_census_not_communicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(verbose_name='Другой парк техники')),
            ],
        ),
        migrations.AddField(
            model_name='census',
            name='b2b',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='census.b2bothers'),
        ),
    ]
