# Generated by Django 4.2.3 on 2024-04-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0030_alter_pointvectorsselectitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
