# Generated by Django 4.2.3 on 2024-01-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0030_b2bothers_census_b2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumeitem',
            name='census',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='census.census'),
        ),
    ]
