# Generated by Django 4.2.3 on 2024-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0032_census_task_author_alter_census_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='worker',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
