# Generated by Django 4.2.3 on 2024-04-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0033_census_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.pointcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='census',
            name='task_author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='census',
            name='worker',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Исполнитель'),
        ),
    ]
