# Generated by Django 4.2.3 on 2024-04-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0035_census_task_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="census",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="census.pointcategory",
                verbose_name="Категория",
            ),
        ),
    ]
