# Generated by Django 4.2.3 on 2024-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0036_alter_census_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
