# Generated by Django 4.2.3 on 2024-05-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_department'),
        ('analytics', '0004_alter_reportonetable_depart'),
        ('census', '0037_volume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='department',
            field=models.ManyToManyField(related_name='cars', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='census',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='department',
            field=models.ManyToManyField(related_name='equipment_list', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='pointcategory',
            name='department',
            field=models.ManyToManyField(related_name='category', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='pointtypes',
            name='department',
            field=models.ManyToManyField(related_name='types', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='pointvectors',
            name='department',
            field=models.ManyToManyField(related_name='vectors', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='pointvectorsselectitem',
            name='department',
            field=models.ManyToManyField(related_name='point_vectors', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='providerlist',
            name='department',
            field=models.ManyToManyField(related_name='providers', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='stotypelist',
            name='department',
            field=models.ManyToManyField(related_name='sto_types', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='department',
            field=models.ManyToManyField(related_name='volume', to='tasks.department', verbose_name='Подразделение'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
