# Generated by Django 4.2.3 on 2024-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0037_alter_census_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='volumes',
            field=models.ManyToManyField(blank=True, default=None, related_name='volumes', to='census.volume'),
        ),
    ]
