# Generated by Django 4.2.3 on 2024-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0038_alter_carslist_department_alter_census_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Адреса из 2GIS',
                'verbose_name_plural': 'Адрес из 2GIS',
                'ordering': ['created_date'],
            },
        ),
    ]
