# Generated by Django 4.2.3 on 2024-01-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0038_census_volumes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='volumes',
        ),
    ]
