# Generated by Django 4.2.3 on 2024-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0039_addressescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='all_volume',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
