# Generated by Django 4.2.3 on 2024-01-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0039_remove_census_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='b2b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='census.b2bothers'),
        ),
    ]
