# Generated by Django 4.2.3 on 2024-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0040_others_all_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='address_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='ID адреса в 1С'),
        ),
    ]
