# Generated by Django 4.2.3 on 2024-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0040_alter_census_b2b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='category',
        ),
        migrations.AddField(
            model_name='census',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='census.pointcategory', verbose_name='Категория'),
        ),
    ]
