# Generated by Django 4.2.3 on 2024-01-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0041_remove_census_category_census_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='category',
        ),
        migrations.AddField(
            model_name='census',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='census.pointcategory', verbose_name='Категория'),
        ),
    ]
