# Generated by Django 4.2.3 on 2024-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0041_alter_census_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LukoilBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Бренды Лукойл',
                'verbose_name_plural': 'Бренды Лукойл',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='census',
            name='load_to_1c',
            field=models.BooleanField(default=False, verbose_name='Загружено'),
        ),
    ]
