# Generated by Django 4.2.3 on 2024-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0042_remove_census_category_census_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='volume',
            field=models.ManyToManyField(blank=True, related_name='census_volumes', to='census.volume'),
        ),
    ]
