# Generated by Django 4.2.3 on 2024-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0042_lukoilbrands_census_load_to_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='lukoilbrands',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
