# Generated by Django 4.2.3 on 2024-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0043_lukoilbrands_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Фасовки масла',
                'verbose_name_plural': 'Фасовки масла',
                'ordering': ['name'],
            },
        ),
    ]
