# Generated by Django 4.2.3 on 2024-01-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0044_alter_census_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorsitem',
            name='census',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='census.census'),
        ),
        migrations.AlterField(
            model_name='census',
            name='vectors',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_vectors', to='census.pointvectorsitem'),
        ),
    ]
