# Generated by Django 4.2.3 on 2024-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0044_oilpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvectorsselectitem',
            name='bonuses',
            field=models.BooleanField(default=False, verbose_name='Бонусная программа'),
        ),
    ]
