# Generated by Django 4.2.3 on 2024-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0045_pointvectorsselectitem_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='kpp',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='census',
            name='lukoil_brands',
            field=models.ManyToManyField(blank=True, default=None, related_name='lukoil_brands', to='census.lukoilbrands'),
        ),
        migrations.AddField(
            model_name='census',
            name='package',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_packages', to='census.oilpackages'),
        ),
    ]
