# Generated by Django 4.2.3 on 2024-01-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0045_pointvectorsitem_census_alter_census_vectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorsitem',
            name='census',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.census'),
        ),
    ]
