# Generated by Django 4.2.3 on 2024-01-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0046_alter_pointvectorsitem_census'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointvectorsitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='pointvectorsitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pointvectorsitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='pointvectorsitem',
            name='census',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='census.census'),
        ),
        migrations.CreateModel(
            name='PointVectorsSelectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('department', models.ManyToManyField(related_name='point_vectors', to='census.department', verbose_name='Подразделение')),
                ('vectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.pointvectors')),
            ],
        ),
        migrations.AddField(
            model_name='pointvectorsitem',
            name='value',
            field=models.ManyToManyField(related_name='vector_items', to='census.pointvectorsselectitem'),
        ),
    ]
