# Generated by Django 4.2.3 on 2024-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0046_census_kpp_census_lukoil_brands_census_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='bonuses',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_bonuses', to='census.providerlist', verbose_name='В бонусных программах каких брендов участвуют?'),
        ),
        migrations.AddField(
            model_name='census',
            name='federal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
