# Generated by Django 4.2.3 on 2024-10-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0047_census_bonuses_census_federal'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='chicago_code',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Код Чикаго'),
        ),
        migrations.AddField(
            model_name='census',
            name='code',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Код 1C'),
        ),
        migrations.AlterField(
            model_name='census',
            name='sto_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='census.stotypelist', verbose_name='Тип СТО'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='name',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Название'),
        ),
    ]
