# Generated by Django 4.2.3 on 2024-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0047_remove_pointvectorsitem_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvectorsitem',
            name='value',
            field=models.ManyToManyField(blank=True, default=None, related_name='vector_items', to='census.pointvectorsselectitem'),
        ),
    ]
