# Generated by Django 4.2.3 on 2024-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0048_census_chicago_code_census_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='bonuses',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_bonuses', to='census.volume', verbose_name='В бонусных программах каких брендов участвуют?'),
        ),
    ]
