# Generated by Django 4.2.3 on 2024-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0050_alter_census_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='bonuses',
            field=models.ManyToManyField(blank=True, default=None, related_name='census_bonuses', to='census.pointvectorsselectitem', verbose_name='В бонусных программах каких брендов участвуют?'),
        ),
    ]
