# Generated by Django 4.2.3 on 2025-01-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_alter_vcard_email_alter_vcard_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vcard',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcard.address'),
        ),
    ]
