# Generated by Django 4.2 on 2023-05-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
        ),
        migrations.CreateModel(
            name="Basics",
            fields=[
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("date", models.DateTimeField(verbose_name="Дата основания")),
                (
                    "number",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("name", models.CharField(max_length=1000, verbose_name="Имя")),
                (
                    "code",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Код 1С",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("name", models.CharField(max_length=1000, verbose_name="Имя")),
                (
                    "code",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Код 1С",
                    ),
                ),
                ("chat_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Телефон"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.worker",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("name", models.CharField(max_length=1000, verbose_name="Имя")),
                (
                    "number",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        default="Новая", max_length=100, verbose_name="Статус"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Исполнить до")),
                ("edited", models.BooleanField(default=False, verbose_name="изменен")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_author",
                        to="tasks.worker",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "author_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_comments",
                        to="tasks.authorcomments",
                        verbose_name="Комментарий автора",
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_tasks",
                        to="tasks.basics",
                        verbose_name="Основание",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        max_length=1000,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_tasks",
                        to="tasks.partner",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_worker",
                        to="tasks.worker",
                        verbose_name="Агент",
                    ),
                ),
                (
                    "worker_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_comments",
                        to="tasks.workercomments",
                        verbose_name="Комментарий исполнителя",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authorcomments",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.worker",
                verbose_name="Автор",
            ),
        ),
    ]
