# Generated by Django 4.0.3 on 2023-06-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': '10. Комментарий автора',
                'verbose_name_plural': '10. Комментарии автора',
            },
        ),
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата основания')),
                ('number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Номер')),
            ],
            options={
                'verbose_name': '02. Основание',
                'verbose_name_plural': '02. Основания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
            ],
            options={
                'verbose_name': '03. Контрагент',
                'verbose_name_plural': '03. Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Электронное письмо'), ('phone', 'Телефонный звонок'), ('meet', 'Личная встреча'), ('e-market', 'Электронная торговая площадка'), ('postmail', 'Почтовое письмо'), ('other', 'Прочее')], default='other', max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('contact_person', models.CharField(max_length=500)),
                ('control_date', models.DateField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_bases', to='tasks.basics', verbose_name='Основание')),
            ],
            options={
                'verbose_name': '08. Результат задач',
                'verbose_name_plural': '08. Результаты задач',
                'ordering': ['base__date'],
            },
        ),
        migrations.CreateModel(
            name='ResultGroup',
            fields=[
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': '07. Группа',
                'verbose_name_plural': '07. Группы',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': '06. Руководитель',
                'verbose_name_plural': '06. Руководители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('chat_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('controller', models.BooleanField(default=False)),
                ('partner', models.CharField(blank=True, max_length=11, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.supervisor')),
            ],
            options={
                'verbose_name': '05. Агент',
                'verbose_name_plural': '05. Агенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.worker', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': '11. Комментарий исполнителя',
                'verbose_name_plural': '11. Комментарии исполнителя',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('number', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='Номер')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('status', models.CharField(default='Новая', max_length=100, verbose_name='Статус')),
                ('deadline', models.DateTimeField(verbose_name='Исполнить до')),
                ('edited', models.BooleanField(default=False, verbose_name='изменен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='tasks.worker', verbose_name='Автор')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='tasks.authorcomments', verbose_name='Комментарий автора')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tasks', to='tasks.basics', verbose_name='Основание')),
                ('partner', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, related_name='partner_tasks', to='tasks.partner', verbose_name='Контрагент')),
                ('result', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='tasks.result')),
                ('worker', models.ForeignKey(default='Удален', on_delete=django.db.models.deletion.CASCADE, related_name='task_worker', to='tasks.worker', verbose_name='Исполнитель')),
                ('worker_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_comments', to='tasks.workercomments', verbose_name='Комментарий исполнителя')),
            ],
            options={
                'verbose_name': '01. Задача',
                'verbose_name_plural': '01. Задачи',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('control_data', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_dates', to='tasks.resultgroup')),
            ],
            options={
                'verbose_name': '09. Результаты-данные групп',
                'verbose_name_plural': '09. Результат-данные группы',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_groups', to='tasks.resultgroup'),
        ),
        migrations.AddField(
            model_name='result',
            name='task_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_task', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='PartnerWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('positions', models.CharField(max_length=1000)),
                ('code', models.CharField(blank=True, max_length=11, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_workers', to='tasks.partner')),
            ],
            options={
                'verbose_name': '04. Сотрудники контрагента',
                'verbose_name_plural': '04. Сотрудники контрагентов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='authorcomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.worker', verbose_name='Автор'),
        ),
    ]
