# Generated by Django 4.2.3 on 2023-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcomments',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='workercomments',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
