# Generated by Django 4.0.3 on 2023-06-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_result_group_basics_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
