# Generated by Django 4.0.3 on 2023-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
