# Generated by Django 4.2.3 on 2023-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='inn',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
