# Generated by Django 4.2 on 2023-05-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_workercomments_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="code",
            field=models.CharField(
                default="Удвлен",
                max_length=11,
                primary_key=True,
                serialize=False,
                verbose_name="Код 1С",
            ),
        ),
        migrations.AlterField(
            model_name="workercomments",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.worker",
                verbose_name="Исполнитель",
            ),
        ),
    ]
