# Generated by Django 4.2.3 on 2023-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_edit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date'], 'verbose_name': '01. Задача', 'verbose_name_plural': '01. Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Изменено'),
        ),
    ]
