# Generated by Django 4.2.3 on 2024-03-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_partner_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerworker',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='tasks.partner'),
        ),
    ]
