# Generated by Django 4.2 on 2023-05-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_worker_code_alter_workercomments_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                default="Удален",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="task_author",
                to="tasks.worker",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="worker",
            field=models.ForeignKey(
                default="Удален",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_worker",
                to="tasks.worker",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="code",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, verbose_name="Код 1С"
            ),
        ),
    ]
