# Generated by Django 4.2.3 on 2024-03-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_partnerworker_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': '06. Руководитель',
                'verbose_name_plural': '06. Руководители',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name'], 'verbose_name': '06. Супервайзер', 'verbose_name_plural': '06. Супервайзеры'},
        ),
        migrations.AddField(
            model_name='supervisor',
            name='head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='tasks.head', verbose_name='РОП'),
        ),
    ]
