# Generated by Django 4.2 on 2023-05-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_author_alter_task_worker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_author",
                to="tasks.worker",
                verbose_name="Автор",
            ),
        ),
    ]
