# Generated by Django 4.2.3 on 2023-10-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_alter_task_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultgroup',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Имя группы'),
        ),
    ]
