# Generated by Django 4.0.3 on 2023-05-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('positions', models.CharField(max_length=1000)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.partner')),
            ],
        ),
    ]
