# Generated by Django 4.2.3 on 2024-05-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.department'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.department'),
        ),
    ]
