# Generated by Django 4.2.3 on 2024-05-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_head_department_supervisor_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '12. Подразделение', 'verbose_name_plural': '12. Подразделения'},
        ),
    ]
