# Generated by Django 4.0.3 on 2023-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_result_control_date_alter_partnerworker_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdata',
            name='control_data',
            field=models.BooleanField(default=False),
        ),
    ]
