# Generated by Django 4.0.3 on 2023-05-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_resultdata_control_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('name', models.CharField(max_length=1000, verbose_name='Имя')),
                ('code', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Код 1С')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.supervisor'),
        ),
    ]
