# Generated by Django 4.2.3 on 2024-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_result_base_alter_result_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
