# Generated by Django 4.2.3 on 2024-09-03 09:08

from django.db import migrations, models
import tasks.services


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_result_base_alter_result_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='secret',
            field=models.CharField(default=tasks.services.create_worker_secret, max_length=50),
        ),
    ]
