# Generated by Django 4.0.3 on 2023-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_worker_controller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorcomments',
            options={'verbose_name': '10. Комментарий автора', 'verbose_name_plural': '10. Комментарии автора'},
        ),
        migrations.AlterModelOptions(
            name='basics',
            options={'ordering': ['-date'], 'verbose_name': '02. Основание', 'verbose_name_plural': '02. Основания'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': '03. Контрагент', 'verbose_name_plural': '03. Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='partnerworker',
            options={'ordering': ['name'], 'verbose_name': '04. Сотрудники контрагента', 'verbose_name_plural': '04. Сотрудники контрагентов'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['base__date'], 'verbose_name': '08. Результат задач', 'verbose_name_plural': '08. Результаты задач'},
        ),
        migrations.AlterModelOptions(
            name='resultdata',
            options={'verbose_name': '09. Результаты-данные групп', 'verbose_name_plural': '09. Результат-данные группы'},
        ),
        migrations.AlterModelOptions(
            name='resultgroup',
            options={'verbose_name': '07. Группа', 'verbose_name_plural': '07. Группы'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name'], 'verbose_name': '06. Руководитель', 'verbose_name_plural': '06. Руководители'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name': '01. Задача', 'verbose_name_plural': '01. Задачи'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name'], 'verbose_name': '05. Агент', 'verbose_name_plural': '05. Агенты'},
        ),
        migrations.AlterModelOptions(
            name='workercomments',
            options={'verbose_name': '11. Комментарий исполнителя', 'verbose_name_plural': '11. Комментарии исполнителя'},
        ),
        migrations.AlterField(
            model_name='result',
            name='control_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='Номер'),
        ),
    ]
