# Generated by Django 4.0.3 on 2023-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_authorcomments_options_alter_basics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerworker',
            name='code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
