# Generated by Django 4.2.3 on 2024-05-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_partner_contract'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_date'], 'verbose_name': 'Реализация', 'verbose_name_plural': 'Реализации'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_date'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='retailunit',
            options={'ordering': ['created_date'], 'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговые точки'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.partner', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='retail_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.retailunit', verbose_name='Торговая точка'),
        ),
    ]
