# Generated by Django 4.2.3 on 2024-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Бренд'),
        ),
    ]
