# Generated by Django 4.2.3 on 2024-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailunit',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='retailunit',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='retailunit',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='retailunit',
            name='vector',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Направление'),
        ),
    ]
