# Generated by Django 4.2.3 on 2024-10-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_orderitem_access_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=2000, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бренды',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.brand', verbose_name='Бренд'),
        ),
    ]
