# Generated by Django 4.2.3 on 2024-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_brand_partkom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='partkom_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Партком'),
        ),
    ]
