# Generated by Django 4.2.3 on 2024-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='partkom_price',
        ),
        migrations.AddField(
            model_name='product',
            name='tranzit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
