# Generated by Django 4.2.3 on 2024-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_price_product_partkom_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
